version = 0.1
[dev.deploy.parameters]
stack_name = "RestaurantsLambdaLayersDev"
resolve_s3 = true
s3_prefix = "RestaurantsLambdaLayersDev"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
image_repositories = []

[prod.deploy.parameters]
stack_name = "RestaurantsLambdaLayersProd"
resolve_s3 = true
s3_prefix = "RestaurantsLambdaLayersProd"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
image_repositories = []