AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
    # デプロイ先環境の設定
    EnvironmentType:
        Type: "String"
        AllowedValues: ["dev", "prod"]

Conditions:
  # 本番環境かどうか
  IsProd: !Equals [!Ref "EnvironmentType", "prod"]

Resources:
    # ホットペッパーAPIクライアント
    HotpepperApiClient:
        Type: "AWS::Serverless::LayerVersion"
        Properties:
            LayerName: !If
                - "IsProd"
                - "RestaurantsHotpepperApiClientProd"
                - "RestaurantsHotpepperApiClientDev"
            ContentUri: "./src/hotpepper_api_client/"
            CompatibleRuntimes:
                - "python3.12"

    # データベースクライアント
    DbClient:
        Type: "AWS::Serverless::LayerVersion"
        Properties:
            LayerName: !If
                - "IsProd"
                - "RestaurantsDbClientProd"
                - "RestaurantsDbClientDev"
            ContentUri: "./src/db_client/"
            CompatibleRuntimes:
                - "python3.12"

Outputs:
    # ホットペッパーAPIクライアントのARN
    ArnHotpepperApiClient:
        Value: !Ref "HotpepperApiClient"
        Export:
            Name: "ArnHotpepperApiClient"

    # データベースクライアントのARN
    ArnDbClient:
        Value: !Ref "DbClient"
        Export:
            Name: "ArnDbClient"
