DynamoDBGcpAddress:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: !If
            - "IsProd"
            - "RestaurantsGcpAddressProd"
            - "RestaurantsGcpAddressDev"
        AttributeDefinitions:
            - AttributeName: "address"
              AttributeType: "S"
        KeySchema:
            - AttributeName: "address"
              KeyType: "HASH"
        BillingMode: "PROVISIONED"
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        DeletionProtectionEnabled: true
