# Lambda
LambdaScrapingDetail:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/scraping_detail/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsScrapingDetailProd"
            - "RestaurantsScrapingDetailDev"
        Role: !GetAtt "IamRoleScrapingDetail.Arn"
        Runtime: "python3.12"
        Layers:
            - !Ref "LambdaLayerDynamodbTypes"
        Environment:
            Variables:
                ARN_LAMBDA_ERROR_COMMON: !GetAtt "LambdaErrorCommon.Arn"
                ARN_LAMBDA_HANDLER_SCHEDULES: !GetAtt "LambdaHandlerSchedules.Arn"
                NAME_IMAGES_BUCKET: !Ref "S3Images"
                NAME_TASK_SCRAPING_DETAIL: !Ref "TaskNameScrapingDetail"
                NAME_DYNAMODB_RESTAURANTS: !Ref "DynamodbRestaurants"
                NAME_DYNAMODB_TABLE_TASKS: !Ref "DynamodbRestaurantsTasks"
                NAME_DYNAMODB_TABLE_IMAGES: !Ref "DynamodbRestaurantsImages"
                NAME_PARAMETER_API_KEY_GOOGLE_GEOCODING: !If
                    - "IsProd"
                    - "/google/geocoding/prod/key"
                    - "/google/geocoding/dev/key"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 600

# IAMロール
IamRoleScrapingDetail:
    Type: "AWS::IAM::Role"
    Properties:
        RoleName: !If
            - "IsProd"
            - "RestaurantsScrapingDetailProd"
            - "RestaurantsScrapingDetailDev"
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Principal:
                      Service: "lambda.amazonaws.com"
                  Action: "sts:AssumeRole"

# IAMポリシー
IamPolicyScrapingDetail:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsScrapingDetailProd"
            - "RestaurantsScrapingDetailDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource:
                      - !GetAtt "LambdaErrorCommon.Arn"
                      - !GetAtt "LambdaHandlerSchedules.Arn"
                - Effect: "Allow"
                  Action:
                      - "s3:ListBucket"
                  Resource: !Sub "arn:aws:s3:::${S3Images}"
                - Effect: "Allow"
                  Action:
                      - "s3:DeleteObject"
                      - "s3:PutObject"
                  Resource: !Sub "arn:aws:s3:::${S3Images}/images/*"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:GetItem"
                      - "dynamodb:PutItem"
                  Resource: !GetAtt "DynamodbRestaurants.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:Query"
                      - "dynamodb:DeleteItem"
                  Resource: !GetAtt "DynamodbRestaurantsTasks.Arn"
                - Effect: "Allow"
                  Action:
                      - "dynamodb:Query"
                      - "dynamodb:DeleteItem"
                      - "dynamodb:BatchWriteItem"
                  Resource: !GetAtt "DynamodbRestaurantsImages.Arn"
                - Effect: "Allow"
                  Action:
                      - "ssm:GetParameter"
                  Resource: !If
                      - "IsProd"
                      - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/google/geocoding/prod/key"
                      - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/google/geocoding/dev/key"
        Roles:
            - !Ref "IamRoleScrapingDetail"