# API
ApiGatewayBackend:
    Type: "AWS::Serverless::Api"
    Properties:
        Name: !If
            - "IsProd"
            - "RestaurantsProd"
            - "RestaurantsDev"
        EndpointConfiguration: "REGIONAL"
        StageName: "v1"
        Cors:
            # 開発環境はローカルからのアクセスも許可する
            # 複数指定できなそうなので、API Gatewayでは全て通してLambda側でチェック
            AllowOrigin: "'*'"
            AllowMethods: "'POST'"
            AllowHeaders: "'Content-Type,X-CSRF-TOKEN'"

# カスタムドメイン
ApiGatewayBackendCustomDomain:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
        DomainName: !If
            - "IsProd"
            - !Sub "restaurants-api.${Domain}"
            - !Sub "restaurants-api-dev.${Domain}"
        EndpointConfiguration:
            Types:
                - "REGIONAL"
        RegionalCertificateArn: !Ref "ArnAcmSslCertficateTokyo"

# APIマッピング
ApiGatewayBackendBasePathMapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
        DomainName: !If
            - "IsProd"
            - !Sub "restaurants-api.${Domain}"
            - !Sub "restaurants-api-dev.${Domain}"
        RestApiId: !Ref "ApiGatewayBackend"
        Stage: "v1"