AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
    # デプロイ先環境の設定
    EnvironmentType:
        Type: "String"
        AllowedValues: ["dev", "prod"]

    # タスク名 - ページごとのタスク登録
    TaskNameRegisterTasksPages:
        Type: "String"

    # タスク名 - 概要情報スクレイピング
    TaskNameScrapingAbstract:
        Type: "String"

    # タスク名 - 詳細情報スクレイピング
    TaskNameScrapingDetail:
        Type: "String"

    # ARN - ACMのSSL証明書 - 東京
    ArnAcmSslCertficateTokyo:
        Type: "String"

    # ARN - ACMのSSL証明書 - バージニア北部
    ArnAcmSslCertficateUsEast:
        Type: "String"

    # SSMパラメータストア名 - Line Notifyシステム通知
    ParameterStoreNameLineNotifyRestaurants:
        Type: "String"

    # SSMパラメータストア名 - Line Notifyエラー通知
    ParameterStoreNameLineNotifyError:
        Type: "String"

    # SSMパラメータストア名 - Line Notify警告通知
    ParameterStoreNameLineNotifyWarning:
        Type: "String"

    # SSMパラメータストア名 - ホットペッパーAPIキー
    ParameterStoreNameHotpepperApiKey:
        Type: "String"

    # SSMパラメータストア名 - GCP APIキー
    ParameterStoreNameGcpApiKey:
        Type: "String"

    # Lambdaレイヤー - Requests
    LambdaLayerRequests:
        Type: "String"
        Default: "arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p312-arm64-requests:7"

    # Lambdaレイヤー - ホットペッパーAPIクライアント
    LambdaLayerHotpepperApiClient:
        Type: "String"

    # Lambdaレイヤー - データベースクライアント
    LambdaLayerSqliteClient:
        Type: "String"

    # Lambdaレイヤー - DynamoDBの型変換
    LambdaLayerDynamodbTypes:
        Type: "String"

    # ドメイン
    Domain:
        Type: "String"

    # Basic認証
    FrontendBasicAuthorization:
        Type: "String"

    # S3バケットプレフィックス
    S3BucketPrefix:
        Type: "String"

    # sqlite3データベースファイル名
    Sqlite3DbFileName:
        Type: "String"
        Default: "database.sqlite3"

    # sqlite3データベースロックファイル名
    Sqlite3DbLockFileName:
        Type: "String"
        Default: "database.sqlite3.lock"

    # ローカル環境のフロントエンドのリファラー（本番では不使用）
    LocalFrontendReferrers:
        Type: "String"

    # 飲食店画像アクセス許可リファラー
    AllowReferersRestaurantImages:
        Type: "String"

Conditions:
    # 本番環境かどうか
    IsProd: !Equals [!Ref "EnvironmentType", "prod"]

Resources:
    # CloudWatchロググループ
    - $file: resources/cloudwatch/log_group.yml

    # EventBridgeスケジュールグループ
    - $file: resources/eventbridge/schedule_group.yml

    # Cloudfront - フロントエンド
    - $file: resources/cloudfront/frontend.yml
    # Cloudfront - 飲食店画像
    - $file: resources/cloudfront/images.yml

    # S3 - データベース
    - $file: resources/s3/database.yml
    # S3 - 画像格納バケット
    - $file: resources/s3/images.yml
    # S3 - フロントエンド
    - $file: resources/s3/frontend.yml

    # DynamoDB
    - $file: resources/dynamodb/restaurants_tasks.yml

    # Route53 - バックエンド
    - $file: resources/route53/backend.yml
    # Route53 - フロントエンド
    - $file: resources/route53/frontend.yml

    # APIGateway - バックエンド
    - $file: resources/apigateway/backend.yml

    # Lambda - LINE通知
    - $file: resources/line_notify.yml

    # Lambda - エラー共通処理
    - $file: resources/error_common.yml

    # EventBridge - スケジュール登録
    - $file: resources/handler_schedules.yml

    # Lambda - ジャンルマスタを更新
    - $file: resources/update_genre_master.yml

    # Lambda - 大サービスエリアマスタを更新
    - $file: resources/update_large_service_area_master.yml

    # Lambda - サービスエリアマスタを更新
    - $file: resources/update_service_area_master.yml

    # Lambda - 大エリアマスタを更新
    - $file: resources/update_large_area_master.yml

    # Lambda - 中エリアマスタを更新
    - $file: resources/update_middle_area_master.yml

    # Lambda - 小エリアマスタを更新
    - $file: resources/update_small_area_master.yml

    # Lambda - 概要一覧ページの登録
    - $file: resources/register_tasks_pages.yml

    # Lambda - 概要情報スクレイピング
    - $file: resources/scraping_abstract.yml

    # Lambda - 詳細情報スクレイピング
    - $file: resources/scraping_detail.yml

    # Lambda - tmpから飲食店テーブルへの更新
    - $file: resources/update_restaurants_from_tmp.yml

    # Lambda - 新規の飲食店通知
    - $file: resources/notify_new_restaurants.yml

    # Lambda - 飲食店一覧情報を取得
    - $file: resources/get_restaurants.yml

Outputs:
    # LINE通知LambdaのARN
    ArnLambdaLineNotify:
        Value: !GetAtt "LambdaLineNotify.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaLineNotify"

    # エラー共通処理LambdaのARN
    ArnLambdaErrorCommon:
        Value: !GetAtt "LambdaErrorCommon.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaErrorCommon"

    # スケジュール登録LambdaのARN
    ArnLambdaHandlerSchedules:
        Value: !GetAtt "LambdaHandlerSchedules.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaRegisterSchedule"

    # ジャンルマスタ更新LambdaのARN
    ArnLambdaUpdateGenreMaster:
        Value: !GetAtt "LambdaUpdateGenreMaster.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaUpdateGenreMaster"

    # 大サービスエリアマスタ更新LambdaのARN
    ArnLambdaUpdateLargeServiceAreaMaster:
        Value: !GetAtt "LambdaUpdateLargeServiceAreaMaster.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaUpdateLargeServiceAreaMaster"

    # サービスエリアマスタ更新LambdaのARN
    ArnLambdaUpdateServiceAreaMaster:
        Value: !GetAtt "LambdaUpdateServiceAreaMaster.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaUpdateServiceAreaMaster"

    # 大エリアマスタ更新LambdaのARN
    ArnLambdaUpdateLargeAreaMaster:
        Value: !GetAtt "LambdaUpdateLargeAreaMaster.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaUpdateLargeAreaMaster"

    # 中エリアマスタ更新LambdaのARN
    ArnLambdaUpdateMiddleAreaMaster:
        Value: !GetAtt "LambdaUpdateMiddleAreaMaster.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaUpdateMiddleAreaMaster"

    # 小エリアマスタ更新LambdaのARN
    ArnLambdaUpdateSmallAreaMaster:
        Value: !GetAtt "LambdaUpdateSmallAreaMaster.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaUpdateSmallAreaMaster"

    # 概要情報スクレイピングタスクの登録（ページごと）LambdaのARN
    ArnLambdaRegisterTasksPages:
        Value: !GetAtt "LambdaRegisterTasksPages.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-LambdaRegisterTasksPages"

    # 概要情報スクレイピングLambdaのARN
    ArnScrapingAbstract:
        Value: !GetAtt "LambdaScrapingAbstract.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-ScrapingAbstract"

    # 詳細情報スクレイピングLambdaのARN
    ArnScrapingDetail:
        Value: !GetAtt "LambdaScrapingDetail.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-ScrapingDetail"

    # 一時テーブルからの飲食店テーブルの更新LambdaのARN
    ArnUpdateRestaurantsFromTmp:
        Value: !GetAtt "LambdaUpdateRestaurantsFromTmp.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-UpdateRestaurantsFromTmp"

    # 新規の飲食店通知LambdaのARN
    ArnNotifyNewRestaurants:
        Value: !GetAtt "LambdaNotifyNewRestaurants.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-NotifyNewRestaurants"

    # 飲食店一覧情報の取得LambdaのARN
    ArnGetRestaurants:
        Value: !GetAtt "LambdaGetRestaurants.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-GetRestaurants"

    # S3データベース格納バケット名
    NameDatabaseBucket:
        Value: !Ref "S3Database"
        Export:
            Name: !Sub "${AWS::StackName}-DatabaseBucketName"

    # S3画像格納バケット名
    NameImagesBucket:
        Value: !GetAtt "S3Images.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-ImagesBucketName"