Route53Backend:
    Type: AWS::Route53::RecordSet
    Properties:
        HostedZoneName: !Sub "${Domain}."
        Name: !If
            - "IsProd"
            - !Sub "restaurants-api.${Domain}."
            - !Sub "restaurants-api-dev.${Domain}."
        Type: A
        AliasTarget:
            DNSName: !GetAtt "ApiGatewayBackendCustomDomain.RegionalDomainName"
            HostedZoneId: !GetAtt "ApiGatewayBackendCustomDomain.RegionalHostedZoneId"
