# API
ApiGatewayBackend:
    Type: "AWS::Serverless::Api"
    Properties:
        Name: !If
            - "IsProd"
            - "RestaurantsProd"
            - "RestaurantsDev"
        EndpointConfiguration: "REGIONAL"
        StageName: "v1"
        Cors:
            AllowOrigin: !Sub "'https://${Route53Frontend}'"
            AllowMethods: "'POST'"
            AllowHeaders: "'Content-Type,X-CSRF-TOKEN'"

# カスタムドメイン
ApiGatewayBackendCustomDomain:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
        DomainName: !If
            - "IsProd"
            - !Sub "restaurants-api.${Domain}"
            - !Sub "restaurants-api-dev.${Domain}"
        EndpointConfiguration:
            Types:
                - "REGIONAL"
        RegionalCertificateArn: !Ref "ArnAcmSslCertficateTokyo"

# APIマッピング
ApiGatewayBackendBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
        DomainName: !Ref ApiGatewayBackendCustomDomain
        RestApiId: !Ref ApiGatewayBackend
        Stage: "v1"