Route53Frontend:
    Type: AWS::Route53::RecordSet
    Properties:
        HostedZoneName: !Sub "${Domain}."
        Name: !If
            - "IsProd"
            - !Sub "restaurants.${Domain}."
            - !Sub "restaurants-dev.${Domain}."
        Type: A
        AliasTarget:
            DNSName: !GetAtt "CloudfrontFrontendDistribution.DomainName"
            # Cloudfrontは「Z2FDTNDATAQYW2」固定
            HostedZoneId: "Z2FDTNDATAQYW2"
