S3Images:
    Type: "AWS::S3::Bucket"
    Properties:
        BucketName: !If
            - "IsProd"
            - !Sub "${S3BucketPrefix}-restaurants-images-prod"
            - !Sub "${S3BucketPrefix}-restaurants-images-dev"