# Lambda
LambdaNotifyNewRestaurants:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/notify_new_restaurants/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsNotifyNewRestaurantsProd"
            - "RestaurantsNotifyNewRestaurantsDev"
        Role: !GetAtt "IamRoleNotifyNewRestaurants.Arn"
        Runtime: "python3.12"
        Layers:
            - !Ref "LambdaLayerSqliteClient"
            - !Ref "LambdaLayerDynamodbTypes"
        Environment:
            Variables:
                ARN_LAMBDA_ERROR_COMMON: !GetAtt "LambdaErrorCommon.Arn"
                ARN_LAMBDA_LINE_NOTIFY: !GetAtt "LambdaLineNotify.Arn"
                NAME_BUCKET_DATABASE: !Ref "S3Database"
                NAME_FILE_DATABASE: !Ref "Sqlite3DbFileName"
                NAME_LOCK_FILE_DATABASE: !Ref "Sqlite3DbLockFileName"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 30

        Events:
            EventBridgeScheduleLambdaNotifyNewRestaurants:
                Type: "ScheduleV2"
                Properties:
                    ScheduleExpression: cron(0 1 ? * SAT *)
                    ScheduleExpressionTimezone: "Asia/Tokyo"
                    State: ENABLED
                    GroupName: !Ref "EventBridgeScheduleGroup"
                    Name: !If
                        - "IsProd"
                        - "NotifyNewRestaurantsProd"
                        - "NotifyNewRestaurantsDev"
                    RoleArn: !GetAtt "IamRoleInvokeNotifyNewRestaurants.Arn"

# IAMロール
IamRoleNotifyNewRestaurants:
    Type: "AWS::IAM::Role"
    Properties:
        RoleName: !If
            - "IsProd"
            - "RestaurantsNotifyNewRestaurantsProd"
            - "RestaurantsNotifyNewRestaurantsDev"
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Principal:
                      Service: "lambda.amazonaws.com"
                  Action: "sts:AssumeRole"

# IAMポリシー
IamPolicyNotifyNewRestaurants:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsNotifyNewRestaurantsProd"
            - "RestaurantsNotifyNewRestaurantsDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource:
                      - !GetAtt "LambdaErrorCommon.Arn"
                      - !GetAtt "LambdaLineNotify.Arn"
                - Effect: "Allow"
                  Action:
                      - "s3:GetObject"
                      - "s3:PutObject"
                  Resource: !Sub "arn:aws:s3:::${S3Database}/${Sqlite3DbFileName}"
                - Effect: "Allow"
                  Action:
                      - "s3:GetObject"
                      - "s3:PutObject"
                      - "s3:DeleteObject"
                  Resource: !Sub "arn:aws:s3:::${S3Database}/${Sqlite3DbLockFileName}"
        Roles:
            - !Ref "IamRoleNotifyNewRestaurants"

# IAMロール
IamRoleInvokeNotifyNewRestaurants:
    Type: "AWS::IAM::Role"
    Properties:
        RoleName: !If
            - "IsProd"
            - "RestaurantsInvokeNotifyNewRestaurantsProd"
            - "RestaurantsInvokeNotifyNewRestaurantsDev"
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Principal:
                      Service: "scheduler.amazonaws.com"
                  Action: "sts:AssumeRole"

# IAMポリシー
IamPolicyInvokeNotifyNewRestaurants:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsInvokeNotifyNewRestaurantsProd"
            - "RestaurantsInvokeNotifyNewRestaurantsDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaNotifyNewRestaurants.Arn"
        Roles:
            - !Ref "IamRoleInvokeNotifyNewRestaurants"