# Lambda
LambdaUpdateMiddleAreaMaster:
    Type: "AWS::Serverless::Function"
    Properties:
        CodeUri: "./lambda_functions/update_middle_area_master/"
        FunctionName: !If
            - "IsProd"
            - "RestaurantsUpdateMiddleAreaMasterProd"
            - "RestaurantsUpdateMiddleAreaMasterDev"
        Role: !GetAtt "IamRoleUpdateMiddleAreaMaster.Arn"
        Runtime: "python3.12"
        Layers:
            - !Ref "LambdaLayerHotpepperApiClient"
            - !Ref "LambdaLayerSqliteClient"
        Environment:
            Variables:
                ARN_LAMBDA_ERROR_COMMON: !GetAtt "LambdaErrorCommon.Arn"
                PARAMETER_STORE_NAME_HOTPEPPER_API_KEY: !Ref "ParameterStoreNameHotpepperApiKey"
                NAME_BUCKET_DATABASE: !Ref "S3Database"
                NAME_FILE_DATABASE: !Ref "Sqlite3DbFileName"
                NAME_LOCK_FILE_DATABASE: !Ref "Sqlite3DbLockFileName"
        Handler: "app.lambda_handler"
        Architectures:
            - "arm64"
        Timeout: 30

        Events:
            EventBridgeScheduleLambdaUpdateMiddleAreaMaster:
                Type: "ScheduleV2"
                Properties:
                    ScheduleExpression: cron(4 0 ? * SUN *)
                    ScheduleExpressionTimezone: "Asia/Tokyo"
                    State: ENABLED
                    GroupName: !Ref "EventBridgeScheduleGroup"
                    Name: !If
                        - "IsProd"
                        - "UpdateMiddleAreaMasterProd"
                        - "UpdateMiddleAreaMasterDev"
                    RoleArn: !GetAtt "IamRoleInvokeUpdateMiddleAreaMaster.Arn"

# IAMロール
IamRoleUpdateMiddleAreaMaster:
    Type: "AWS::IAM::Role"
    Properties:
        RoleName: !If
            - "IsProd"
            - "RestaurantsUpdateMiddleAreaMasterProd"
            - "RestaurantsUpdateMiddleAreaMasterDev"
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Principal:
                      Service: "lambda.amazonaws.com"
                  Action: "sts:AssumeRole"

# IAMポリシー
IamPolicyUpdateMiddleAreaMaster:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsUpdateMiddleAreaMasterProd"
            - "RestaurantsUpdateMiddleAreaMasterDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "ssm:GetParameter"
                  Resource:
                      - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStoreNameHotpepperApiKey}"
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource:
                      - !GetAtt "LambdaErrorCommon.Arn"
                - Effect: "Allow"
                  Action:
                      - "s3:GetObject"
                      - "s3:PutObject"
                  Resource: !Sub "arn:aws:s3:::${S3Database}/${Sqlite3DbFileName}"
                - Effect: "Allow"
                  Action:
                      - "s3:GetObject"
                      - "s3:PutObject"
                      - "s3:DeleteObject"
                  Resource: !Sub "arn:aws:s3:::${S3Database}/${Sqlite3DbLockFileName}"
        Roles:
            - !Ref "IamRoleUpdateMiddleAreaMaster"

# スケジュール実行IAMロール
IamRoleInvokeUpdateMiddleAreaMaster:
    Type: "AWS::IAM::Role"
    Properties:
        RoleName: !If
            - "IsProd"
            - "RestaurantsInvokeUpdateMiddleAreaMasterProd"
            - "RestaurantsInvokeUpdateMiddleAreaMasterDev"
        AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Principal:
                      Service: "scheduler.amazonaws.com"
                  Action: "sts:AssumeRole"

# スケジュール実行IAMポリシー
IamPolicyInvokeUpdateMiddleAreaMaster:
    Type: "AWS::IAM::Policy"
    Properties:
        PolicyName: !If
            - "IsProd"
            - "RestaurantsInvokeUpdateMiddleAreaMasterProd"
            - "RestaurantsInvokeUpdateMiddleAreaMasterDev"
        PolicyDocument:
            Version: "2012-10-17"
            Statement:
                - Effect: "Allow"
                  Action:
                      - "lambda:InvokeFunction"
                  Resource: !GetAtt "LambdaUpdateMiddleAreaMaster.Arn"
        Roles:
            - !Ref "IamRoleInvokeUpdateMiddleAreaMaster"