CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
        LogGroupName: !If
            - "IsProd"
            - "RestaurantsProd"
            - "RestaurantsDev"
        RetentionInDays: 7